### ISSUE TITLE
CommentStream appears to drop a significant amount of comments from /r/all.

### ISSUE THREAD

**Issue by Orbyt** [MayorMonty/Snoostorm#47]
When listening for comments on /r/all, `CommentStream` appears to drop a significant number of comments when compared to comment streams created by accessing the Reddit API via other means. I created two simple scripts, one in Node.js utilizing Snoostorm, and one in Python using the very popular PRAW module. Both scripts listened for comments on /r/all and printed comment IDs to a file.

The results from PRAW surfaced a very large number of comments that were not present in the results from the script utilizing Snoostorm.

```javascript
const r = new Snoowrap({
    userAgent: 'reddit-bot-example-node',
    clientId: CLIENT_ID,
    clientSecret: CLIENT_SECRET,
    username: REDDIT_USER,
    password: REDDIT_PASS
});

const stream = new CommentStream(r, { subreddit: "all"});
stream.on("item", comment => {
    fs.appendFile('results.txt', comment.id + " " + comment.permalink +"\n", function (err) {
        if (err) throw err;
        console.log('Saved!');
    });
})
```

**Comment by Orbyt** [comment]
Explicitly specifying a limit of 100 via `CommentStream(r, { subreddit: "all", limit: 100, pollTime: 2000,})` appears to return a number of comments similar to the number of comments returned when using other methods.

**Comment by MayorMonty** [comment]
The current default options for new comment streams are as follows

```TypeScript
export const DefaultOptions: SnooStormOptions = {
  pollTime: 2000,
  limit: 5,
  subreddit: "all",
};
```

This is mostly a remnant from the old API limits. The new API limits (when connected via Oath2) support up to 60 requests per minute, and each comment returned counted as a ratelimit (if I'm remembering correctly, I wrote that code years ago). Therefore, Snoostorm is designed to have up to 2 simultaneous streams running without issue. 

However, because the API ratelimit has changed, it makes sense to up the limit. This should be updated in the next patch version.
